// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data;

#nullable disable

namespace ToDoApp.Migrations
{
    [DbContext(typeof(ToDoAppDbContext))]
    [Migration("20231027130212_FinalNamingFix")]
    partial class FinalNamingFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("ToDoApp.Data.Models.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2024, 1, 25, 15, 2, 12, 22, DateTimeKind.Local).AddTicks(9310),
                            Name = "Get AWS Certified"
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2023, 11, 8, 15, 2, 12, 22, DateTimeKind.Local).AddTicks(9360),
                            Name = "Book off days"
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2023, 11, 7, 15, 2, 12, 22, DateTimeKind.Local).AddTicks(9360),
                            Name = "Read a book"
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2023, 11, 17, 15, 2, 12, 22, DateTimeKind.Local).AddTicks(9360),
                            Name = "Pay Electricity bill"
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2023, 10, 28, 15, 2, 12, 22, DateTimeKind.Local).AddTicks(9360),
                            Name = "Get Groceries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
