// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Data;

#nullable disable

namespace ToDoApp.Migrations
{
    [DbContext(typeof(ToDoAppDbContext))]
    partial class ToDoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("ToDoApp.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2024, 1, 25, 11, 38, 27, 187, DateTimeKind.Local),
                            Name = "Get AWS Certified"
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2023, 11, 8, 11, 38, 27, 187, DateTimeKind.Local).AddTicks(50),
                            Name = "Book off days"
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2023, 11, 7, 11, 38, 27, 187, DateTimeKind.Local).AddTicks(50),
                            Name = "Read a book"
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2023, 11, 17, 11, 38, 27, 187, DateTimeKind.Local).AddTicks(50),
                            Name = "Pay Electricity bill"
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2023, 10, 28, 11, 38, 27, 187, DateTimeKind.Local).AddTicks(60),
                            Name = "Get Groceries"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
